### ISSUE TITLE
Re-assess port

### ISSUE THREAD

**Issue by addyosmani** [GoogleWebComponents/google-sheets#20]
We had to pull this from google-web-components as it was breaking the catalog. The culprit is a bad merge from https://github.com/GoogleWebComponents/google-sheets/commit/55ef6e0fffea325f8e46ed61aad922a758c34162 which includes some merge conflicts.

I stepped back through history trying to get the port working but was unable to. Filing for us to look at post I/O.

**Comment by ebidel** [comment]
Should be fixed up now.
