### ISSUE TITLE
Demo not fully funcitonal

### ISSUE THREAD

**Issue by atotic** [GoogleWebComponents/google-sheets#21]
Upon loading, no data is loaded until one clicks on "View tab 2 data"

**Comment by eaflores4** [comment]
Also if you change tab-id="2" no data is loaded until you click on "View tab 1 data"

**Comment by ebidel** [comment]
The observers was wanting a number of params before it was called:

    observers: [		
      '_configUpdate(key published tabId clientId)'		
    ],

Added individual ones so the config update is seen. Demo should be working in master
